### PR TITLE
Added draft-ounsworth-pq-external-pubkeys

### PR DESCRIPTION
**Pull request by ounsworth**
This is a draft I wrote in 2021 that was brought up to me recently. Apparently BouncyCastle has implemented this on the demand of one of their customers.

### CODE REVIEW

**Comment by paulehoffman** [comment]
Please update this listing to indicate that it is an abandoned draft

**Comment by ounsworth** [comment]
Added an "Expired" notice.
Though I am currently on the phone with David Hook about reviving it. I guess I can remove the "Expired" notice if / when we submit an -01.

**Comment by paulehoffman** [comment]
Well, let's leave this open until you know whether you will revive it.

**Comment by ounsworth** [comment]
We have revived it!

* Draft: https://datatracker.ietf.org/doc/draft-ounsworth-lamps-pq-external-pubkeys/00/
* LAMPS list: https://mailarchive.ietf.org/arch/msg/spasm/6QzcEuoXF6oQe5SB2vhHTE-bu-I/
* TLS list: https://mailarchive.ietf.org/arch/msg/tls/MhZdqdaFNK00wOAZ2W_sOCOk_8M/

**Pull request merged**
