### PR TITLE
Add MLS to the list of PQC-compatible protocol efforts

### PR DESCRIPTION
**Pull request by bifurcation**

### CODE REVIEW

**Comment by csosto-pk** [comment]
Good idea! 

@bifurcation I think a new draft for PQ-hybrid HPKE (no _auth_ modes, just _base_ and _PSK_ a la  [ia.cr/2022/414](https://eprint.iacr.org/2022/414) ) is warranted here. It would benefit ECH, MLS and other places imo. 

What do you think?

**Comment by bifurcation** [comment]
I don't think we need to update HPKE for that, just define and register the KEM.  It should be straightforward to document (e.g., using the [Ounsworth CFRG draft](https://datatracker.ietf.org/doc/draft-ounsworth-cfrg-kem-combiners/)), and the HPKE KEM registry is Specification Required, so you don't even need an RFC.

**Comment by claucece** [comment]
Merging now! Thank you!

**Comment by bifurcation** [comment]
@csosto-pk - note that a [draft describing X25519+Kyber768 hybrid HPKE](https://datatracker.ietf.org/doc/draft-westerbaan-cfrg-hpke-xyber768d00) (heh) was recently posted

**Pull request merged**
